name: molgpt
channels:
    - pytorch
    - conda-forge
dependencies:
    - python=3.10
    - cudatoolkit=11.3
    - pytorch=1.12.1=py3.10_cuda11.3_cudnn8.3.2_0
    - pandas
    - matplotlib
    - seaborn
    - rdkit
    - numpy
    - jupyter
    - json
    - wandb
    - tqdm
    - molsets=0.3.1
    - guacamol=0.5.2
    - pip
